/**
 * A very basic build pipeline with commit, test and release jobs.
 */

job('commit') {
  description 'Build source code and run unit tests'

  scm {
    github('Praqma/automated-branch-pipelines')
  }

  steps {
    shell('echo Generated by the commit job > commit-artifact.txt')
  }

  publishers {
    archiveArtifacts {
      pattern('commit-artifact.txt')
    }
  }
}

job('test') {
  description 'Acceptance tests'

  steps {
    copyArtifacts('commit') {
      includePatterns('commit-artifact.txt')
    }
    shell('cat commit-artifact.txt')
  }
}

job('release') {
  description 'Package a release'

  steps {
    copyArtifacts('commit') {
      includePatterns('commit-artifact.txt')
    }
    shell('cp commit-artifact.txt release-artifact.txt')
  }

  publishers {
    archiveArtifacts {
      pattern('release-artifact.txt')
    }
  }
}
